openapi: 3.1.0
info:
  title: Profiler Events
  version: 1.0.0
  description: OpenAPI definition for Profiler event payloads (async communication)


paths: {}

components:
  schemas:
    UserPermissionCreatedEvent:
      type: object
      properties:
        userEmail:
          type: string
        bankCode:
          type: string
        sectionPermissions:
          type: array
          items:
            $ref: '#/components/schemas/SectionPermission'
      required:
        - userEmail
        - bankCode
        - sectionPermissions

    UserPermissionUpdatedEvent:
      type: object
      properties:
        userEmail:
          type: string
        bankCode:
          type: string
        sectionPermissions:
          type: array
          items:
            $ref: '#/components/schemas/SectionPermission'
      required:
        - userEmail
        - bankCode
        - sectionPermissions

    #    Payloads objects
    SectionPermission:
      type: object
      properties:
        sectionCode:
          type: string
        sectionName:
          type: string
        featurePermissions:
          type: array
          items:
            $ref: '#/components/schemas/FeaturePermission'
      required:
        - sectionCode
        - sectionName
        - featurePermissions
    FeaturePermission:
      type: object
      properties:
        featureCode:
          type: string
        featureName:
          type: string
        permissions:
          type: array
          items:
            type: string
      required:
        - featureCode
        - featureName
        - permissions

