version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - 9091:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - kafka

  postgres-proposal:
    image: postgres:15
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: proposaldb
    ports:
      - 5433:5432

  postgres-portfolio:
    image: postgres:15
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: portfoliodb
    ports:
      - 5434:5432

  postgres-customer:
    image: postgres:15
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: customerdb
    ports:
      - 5435:5432

  postgres-product:
    image: postgres:15
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: productdb
    ports:
      - 5436:5432

  postgres-order:
    image: postgres:15
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: orderdb
    ports:
      - 5437:5432

  postgres-advisor:
    image: postgres:15
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: advisordb
    ports:
      - 5438:5432

  postgres-reporting:
    image: postgres:15
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: reportingdb
    ports:
      - 5439:5432

  postgres-notification:
    image: postgres:15
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: notificationdb
    ports:
      - 5440:5432

  postgres-profiler:
    image: postgres:15
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: profilerdb
    ports:
      - 5441:5432

  postgres-user:
    image: postgres:15
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: userdb
    ports:
      - 5442:5432

  splunk:
    image: splunk/splunk:latest
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=password
      - SPLUNK_HEC_TOKEN=12345678-1234-1234-1234-1234567890ab
      - SPLUNK_HEC_PORT=9090
      - TZ=Europe/Rome
    ports:
      - 8000:8000   # Splunk Web UI
      - 9090:9090   # HTTP Event Collector (HEC)
      - 9997:9997   # Splunk Forwarder
    volumes:
      - splunk-data:/opt/splunk/var
      - ./logs/:/logs/
    restart: unless-stopped

#FIXME: The Splunk Forwarder service is configured to monitor the /logs/ directory but it's not showing up in the Splunk UI.
  splunk-forwarder:
    image: splunk/universalforwarder:latest
    user: root
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=password
      - SPLUNK_ADD=monitor /logs/ -sourcetype _json  -index main -auth admin:password
      - SPLUNK_FORWARD_SERVER=splunk:9997
      - TZ=Europe/Rome
      - SPLUNK_DEBUG=true
    volumes:
      - ./logs/:/logs/
    depends_on:
      - splunk


volumes:
  splunk-data:
    driver: local
