openapi: 3.1.0
info:
  title: Bank Apis
  version: 1.0.0
  description: API for managing bank information.


paths: {}

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas: {}