security:
  jwt:
    publicKeyPath: classpath:jwt/public_key.pem
    header: Authorization
    prefix: Bearer

spring:
  mustache:
    check-template-location: false
  config:
    import: classpath:kafka-shared-properties.yaml