openapi: 3.1.0
info:
  title: Customer Apis
  version: 1.0.0
  description: API for managing customer information.

paths:
  /customer/init:
    post:
      summary: Initialize a new customer onboarding
      description: Receives the personal data of a customer to start the onboarding process.
      operationId: initCustomer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerDTO'
      responses:
        '200':
          description: Customer onboarding initialized successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerDTO'
        '400':
          description: Invalid input data
        '500':
          description: Internal server error
      tags:
        - Customer

  /financial/types:
    get:
      summary: Get all financial types
      description: Returns the list of all available financial types.
      operationId: getAllFinancialTypes
      responses:
        '200':
          description: List of financial types
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FinancialTypeDTO'

      tags:
        - Financial

  /goal/types:
    get:
      summary: Get all goal types
      description: Returns the list of all available goal types.
      operationId: getAllGoalTypes
      responses:
        '200':
          description: List of goal types
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GoalTypeDTO'
      tags:
        - Goal

  /customer/{customerId}/financials:
    post:
      summary: Add financial data for a customer
      description: Adds a list of financial records for the specified customer.
      operationId: addCustomerFinancials
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CustomerFinancialDTO'
      responses:
        '200':
          description: Financial records created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerDTO'
      tags:
        - Customer

  /customer/{customerId}/goals:
    post:
      summary: Add goals for a customer
      description: Adds a list of goals for the specified customer.
      operationId: addCustomerGoals
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CustomerGoalDTO'
      responses:
        '201':
          description: Goals created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerDTO'
      tags:
        - Customer

components:
  schemas:
    CustomerDTO:
      type: object
      required:
        - customerType
        - taxId
        - customerStatus
        - userId
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the customer
        userId:
          type: string
          format: uuid
          description: Unique identifier for the user associated with the customer
        customerType:
          $ref: '#/components/schemas/CustomerType'
        firstName:
          type: string
        lastName:
          type: string
        dateOfBirth:
          type: string
          format: date
        gender:
          $ref: '#/components/schemas/Gender'
        nationality:
          type: string
          description: ISO 3166-1 alpha-2
          maxLength: 2
        companyName:
          type: string
        taxId:
          type: string
        phoneNumber:
          type: string
        addressLine1:
          type: string
        addressLine2:
          type: string
        city:
          type: string
        zipCode:
          type: string
        country:
          type: string
          description: ISO 3166-1 alpha-2
          maxLength: 2
        customerStatus:
          $ref: '#/components/schemas/CustomerStatus'
        onboardingDate:
          type: string
          format: date
        customerFinancials:
          type: array
          items:
            $ref: '#/components/schemas/CustomerFinancialDTO'
        customerGoals:
          type: array
          items:
            $ref: '#/components/schemas/CustomerGoalDTO'

    CustomerType:
      type: string
      enum:
        - INDIVIDUAL
        - CORPORATE

    Gender:
      type: string
      enum:
        - MALE
        - FEMALE
        - OTHER
        - NOT_SPECIFIED

    CustomerStatus:
      type: string
      enum:
        - DRAFT
        - PENDING_VERIFICATION
        - ACTIVE
        - REJECTED

    FinancialTypeDTO:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
          description: Financial type (e.g. INCOME, EXPENSE)
        description:
          type: string

    GoalTypeDTO:
      type: object
      properties:
        name:
          type: string
        description:
          type: string

    CustomerFinancialDTO:
      type: object
      required:
          - financialType
          - amount
          - date
      properties:
        financialType:
          $ref: '#/components/schemas/FinancialTypeDTO'
        amount:
          type: number
        description:
          type: string
          maxLength: 500
        notes:
          type: string
          maxLength: 500

    CustomerGoalDTO:
      type: object
      required:
          - goalType
          - targetAmount
          - goalTimeLine
      properties:
        goalType:
          $ref: '#/components/schemas/GoalTypeDTO'
        targetAmount:
          type: number
        notes:
          type: string
          maxLength: 500
        goalTimeLine:
          type: string
          description: Duration of the goal in months or years
