openapi: 3.0.4
info:
  title: Document Events
  version: 1.0.0
  description: OpenAPI definition for document event payloads (async communication)
  contact:
    name: RaffSStein
    url: https://github.com/RaffSStein
    email: raffaele.princee@gmail.com
  license:
    name: MIT License
    url: https://opensource.org/license/mit/


paths: {}

components:
  schemas: {}