server:
  port: 8081
spring:
  application:
    name: proposal-service
  datasource:
    url: jdbc:postgresql://localhost:5433/proposaldb
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

