openapi: 3.1.0
info:
  title: Profiler APIs
  version: 1.0.0
  description: |
    API for managing and retrieving the sitemap, sections, features, and permissions for applications and users.
    
    The following APIs (capabilities) are exposed by the profiler:
    - API to retrieve the sitemap of an application
    - API to retrieve the sitemap, including permissions, for a given user
    - API to modify the sitemap/permissions for a given user

servers:
  - url: https://WIP

paths:
  /sitemap/{application}:
    get:
      summary: Get the complete sitemap for a specific application
      operationId: getSitemap
      tags:
        - Sitemap
      parameters:
        - name: application
          in: path
          required: true
          description: Application identifier (e.g. "b2c", "backoffice")
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Sitemap for the requested application
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SitemapResponse'
        '401':
          description: Unauthorized

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    SitemapResponse:
      type: object
      properties:
        application:
          type: string
        sections:
          type: array
          items:
            $ref: '#/components/schemas/Section'

    Section:
      type: object
      properties:
        id:
          type: string
          format: uuid
        sectionCode:
          type: string
        sectionName:
          type: string
        features:
          type: array
          items:
            $ref: '#/components/schemas/Feature'


    Feature:
      type: object
      properties:
        id:
          type: string
          format: uuid
        featureCode:
          type: string
        featureName:
          type: string

    Permission:
      type: object
      properties:
        id:
          type: string
          format: uuid
        permissionCode:
          type: string
        permissionName:
          type: string
