openapi: 3.1.0
info:
  title: User Events
  version: 1.0.0
  description: OpenAPI definition for Proposal event payloads (async communication)


paths: {}

components:
  schemas:
    UserCreatedEvent:
      type: object
      properties:
        email:
          type: string
      required:
        - email
    UserUpdatedEvent:
      type: object
      properties:
        email:
          type: string
#      required:
#        - proposalId
#        - status
#        - updatedAt
