openapi: 3.1.0
info:
  title: User Events
  version: 1.0.0
  description: OpenAPI definition for Proposal event payloads (async communication)


paths: {}

components:
  schemas:
    UserCreatedEvent:
      type: object
      properties:
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        createdAt:
          type: string
          format: date-time
      required:
        - email
        - firstName
        - lastName
        - createdAt


    UserUpdatedEvent:
      type: object
      properties:
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        updatedAt:
          type: string
          format: date-time
      required:
        - email
        - firstName
        - lastName
        - updatedAt
